name: example
description: "This is an example on how to use the typesafe, reactive and lightweight SQLite abstraction within your Flutter applications."
homepage: https://pinchbv.github.io/floor/
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  floor:
    path: ../floor/
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  analyzer: ^7.0.0
  build_runner: ^2.4.15
  floor_generator:
    path: ../floor_generator/

flutter:
  uses-material-design: true
