name: floor
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 1.5.0
homepage: https://pinchbv.github.io/floor/
repository: https://github.com/pinchbv/floor
issue_tracker: https://github.com/pinchbv/floor/issues
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  collection: ^1.19.1
  floor_annotation:
    path: ../floor_annotation/
  floor_common:
    path: ../floor_common/
  flutter:
    sdk: flutter
  meta:
  path: ^1.9.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  sqflite_common_ffi_web: ^1.0.0
  sqlparser: ^0.41.0

dev_dependencies:
  build_runner: ^2.4.15
  floor_generator:
    path: ../floor_generator
  flutter_test:
    sdk: flutter
  matcher: ^0.12.17
  mockito: ^5.4.5