name: floor_common
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 1.2.0
homepage: https://floor.codes
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  floor_annotation:
    path: ../floor_annotation/
  meta:
  path: ^1.9.1
  sqflite_common: ^2.5.5
  sqlparser: ^0.41.0

dev_dependencies:
  build_runner: ^2.4.15
  collection: ^1.19.1
  floor_generator:
    path: ../floor_generator/
  sqflite_common_ffi: ^2.3.5
  test: ^1.25.15
  matcher: ^0.12.17
  mockito: ^5.4.5
